name: getPrUrl

on: [pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: getPrUrl
        id: pr-url
        uses: ./
      - name: display
        run: echo ${{ steps.pr-url.outputs.url }}
  